"""Bridge that makes the Nix-built GNU Radio environment available to Bazel.

`bazel build //...` on a machine without Nix stays green *until* a target pulls
in `@grenv`; only the flowgraph py_binary targets do. When one does, this
repository rule runs `nix build .#grenv` against the repo's own flake (pinned by
flake.lock) and exposes the resulting Python 3.11 site-packages directory.

Rather than copy GNU Radio's multi-gigabyte closure into every target's runfiles,
we hand Bazel the absolute `/nix/store/...` path (via a generated `grenv_path.py`)
and prepend it to `sys.path` at runtime -- see //sdr:gnuradio_env. The Nix store
is a stable, content-addressed, host-global location, and GNU Radio's `.so`s carry
absolute RPATHs into that store, so nothing else needs to travel in runfiles.
"""

_BUILD_FILE = '''\
# Generated by //nix:grenv.bzl. Do not edit.
load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

# Exposes the module `grenv_path` (SITE_PACKAGES, PREFIX constants) to Python.
py_library(
    name = "grenv",
    srcs = ["grenv_path.py"],
    imports = ["."],
)

exports_files(["grenv_path.py"])
'''

def _grenv_repo_impl(ctx):
    nix = ctx.which("nix")
    if nix == None:
        fail(
            "`nix` was not found on PATH. The GNU Radio flowgraph targets require " +
            "Nix (they build @grenv from //:flake.nix). Install Nix, or build only " +
            "the non-SDR targets.",
        )

    # Copy the flake into this repo dir so `nix build path:.` copies ONLY the
    # flake files into the store -- not the whole (cache-laden) workspace. Using
    # ctx.read pins the repo to the flake's contents: edit either file and Bazel
    # refetches.
    ctx.file("flake.nix", ctx.read(ctx.attr.flake_nix))
    ctx.file("flake.lock", ctx.read(ctx.attr.flake_lock))

    repo_dir = str(ctx.path("."))
    result = ctx.execute(
        [
            nix,
            "build",
            "path:{}#{}".format(repo_dir, ctx.attr.attr),
            "--no-link",
            "--print-out-paths",
            "--extra-experimental-features",
            "nix-command flakes",
        ],
        # GNU Radio's closure is cached, but a cold cache still downloads ~800 MiB.
        timeout = 3600,
        quiet = False,
    )
    if result.return_code != 0:
        fail("`nix build .#{}` failed:\n{}".format(ctx.attr.attr, result.stderr))

    out_path = result.stdout.strip().split("\n")[-1].strip()
    if not out_path.startswith("/nix/store/"):
        fail("Unexpected `nix build` output (no store path):\n{}".format(result.stdout))

    site_packages = "{}/lib/python{}/site-packages".format(out_path, ctx.attr.python_version)
    if not ctx.path(site_packages).exists:
        fail("site-packages not found in the GNU Radio env: {}".format(site_packages))

    # A convenience symlink for humans poking at the repo; not used at runtime.
    ctx.symlink(out_path, "env")

    ctx.file(
        "grenv_path.py",
        "# Generated by //nix:grenv.bzl. Do not edit.\n" +
        "PREFIX = " + repr(out_path) + "\n" +
        "SITE_PACKAGES = " + repr(site_packages) + "\n",
    )
    ctx.file("BUILD.bazel", _BUILD_FILE)

_grenv_repo = repository_rule(
    implementation = _grenv_repo_impl,
    attrs = {
        "attr": attr.string(default = "grenv", doc = "Flake package attribute to build."),
        "python_version": attr.string(default = "3.11"),
        "flake_nix": attr.label(default = "//:flake.nix"),
        "flake_lock": attr.label(default = "//:flake.lock"),
    },
    # Re-run on `bazel sync --configure` (e.g. after the store path is GC'd) and
    # keep it off the remote cache -- the output is a host-local store path.
    configure = True,
    local = True,
)

def _grenv_ext_impl(_ctx):
    _grenv_repo(name = "grenv")

grenv = module_extension(implementation = _grenv_ext_impl)
